version: '2.3'
services:
  backend:
    image: messageboard-backend
    build:
      context: .
      dockerfile: ./docker/images/java
    ports:
      - 8080:8080
    working_dir: /backend
    command: ./gradlew bootRun --args='--spring.profiles.active=docker'