version: '2.3'
services:
  app:
    image: messageboard-app
    build:
      context: .
      dockerfile: ./docker/images/java
    ports:
      - 8080:8080
    volumes:
      - .:/app:delegated
    working_dir: /app
    command: ./gradlew clean bootRun --args='--spring.profiles.active=docker'