create sequence user_sequence_generator start with 50 increment by 50;

create table messages (id bigint generated by default as identity, created_by varchar(50) not null, created_timestamp timestamp not null, last_modified_by varchar(50), last_modified_timestamp timestamp, text varchar(255) not null, user_id bigint, primary key (id));

create table users (id bigint not null, created_by varchar(50) not null, created_timestamp timestamp not null, last_modified_by varchar(50), last_modified_timestamp timestamp, password varchar(255) not null, username varchar(255) not null, primary key (id));

alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);

alter table messages add constraint FKpsmh6clh3csorw43eaodlqvkn foreign key (user_id) references users on delete cascade;