version: '2.3'
services:
  webapp:
    image: messageboard-webapp
    build:
      context: .
      dockerfile: docker/images/node-local
      args:
        - API_BASE_URL=${API_BASE_URL-http://localhost:8080/api}
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./:/webapp:delegated
    working_dir: /webapp
    command: sh -c 'yarn install && yarn run build && yarn global add serve && serve -s build -l 5000'